cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'vim'
brew 'macvim', args: ['override-system-vim']
brew 'git'
brew 'legit'
brew 'zsh'
brew 'tmux'
brew 'ack'
brew 'ssh-copy-id'
brew 'tree'
brew 'p7zip'
brew 'wget'
brew 'libev'

brew 'python3'
brew 'node'
brew 'sbt'
brew 'scala'

brew 'awscli'
brew 'pgcli'
brew 'postgresql'
brew 'mongodb'
brew 'cassandra'
brew 'apache-spark'

cask 'transmission'
cask 'vlc'
cask 'iterm2'
cask 'calibre'
cask 'flux'
cask 'android-file-transfer'
cask 'imageoptim'
cask 'appcleaner'
