" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Relode .vimrc.
map <silent> <F12> :source ~/.vimrc<cr>

" Jump between splits easely.
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Disable arrow keys
map <Left>  <Nop>
map <Right> <Nop>
map <Up>    <Nop>
map <Down>  <Nop>

" Remap ESC
imap jj <ESC>

" Remap column (super) symbol to semicolin.
nore ; :
nore , ;

" Common typos fixes.
:command WQ wq
:command Wq wq
:command W w
:command Q q

" General config
set nowrap
set nonumber
set backspace=2
set laststatus=2                "display the status line always
set confirm
set scrolloff=2                 "auto scroll text
set modeline                    "enable modline
set encoding=utf-8              "deflault encouding
set autowrite                   "prevent asking if you want to save the curbuf
set sidescrolloff=5             "always at least five lines visible above/below
set virtualedit=block           "cursr can be positioned where there is no char
set splitright                  "make the new window appear on the right
set splitbelow                  "show split screens at the bottom of the screen
filetype indent on

" Colorscheme
syntax enable                   "turn on syntax highlighting
set background=light            "set background

" Searching
set ignorecase                  "case insensitive search
set smartcase                   "if uppercase letter, it is case sensitive
set incsearch                   "move the cursor to the matched string
set hlsearch                    "highlight search matches

" Indentation
set tabstop=2                   "set how many columns a tab counts for
set expandtab                   "insert spaces on tab
set softtabstop=2               "set how many columns vim inserts on tab
set shiftwidth=2                "how many columns with >> and <<

" Title
set title                       "automaticly set vim windows title
set titlestring=VIM:\ %F

" Swap file location
set backupdir=~/.backup,.,/tmp
set directory=~/.backup,/tmp

set foldmethod=marker          "special chars to flag the start and end of fold
set mouse=a

if exists('+colorcolumn')
    set colorcolumn=80
endif

" Sierra regression
set clipboard=unnamed

