" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" ================ Vundle Plugins ================

filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'tpope/vim-surround'
Plugin 'bling/vim-airline'
Plugin 'elzr/vim-json'
Plugin 'groenewege/vim-less'
Plugin 'plasticboy/vim-markdown'
Plugin 'airblade/vim-gitgutter'
Plugin 'jnwhiteh/vim-golang'
Plugin 'mileszs/ack.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'Raimondi/delimitMate'
Plugin 'mfukar/robotframework-vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'nono/vim-handlebars'
Plugin 'nanotech/jellybeans.vim'
Plugin 'Shougo/unite.vim'
Plugin 'Valloric/YouCompleteMe'

" end of Plugins
call vundle#end()
filetype plugin indent on

" ================ Plugin Settings ===============

" Pathogen.
execute pathogen#infect()

" Unite
let g:unite_source_history_yank_enable = 1
call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <leader>e :<C-u>Unite -buffer-name=buffer  buffer<cr>

" vim-airline
let g:airline_powerline_fonts = 1

" vim-ctrlp
let g:ctrlp_max_files = 0
let g:ctrlp_max_depth = 100

" vim-gitgutter
" disable plugins keymaps
let g:gitgutter_map_keys = 0
map <F5> :GitGutterToggle<cr>

" YouCompleteMe
" set default conf file
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
let g:ycm_auto_trigger = 0      "turn off auto trigger
let g:ycm_autoclose_preview_window_after_insertion = 1

" ================ General Settings ==============

" Relode .vimrc.
map <silent> <F12> :source ~/.vimrc<cr>

" Jump between splits easely.
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Disable arrow keys
map <Left>  <Nop>
map <Right> <Nop>
map <Up>    <Nop>
map <Down>  <Nop>

" set mouse gui options
map <F8> :set mouse=r<cr>
map <F9> :set mouse=a<cr>

" Remap column (super) symbol to semicolin.
nore ; :
nore , ;

" Common typos fixes.
:command WQ wq
:command Wq wq
:command W w
:command Q q

iab anf and
iab adn and
iab ans and
iab teh the
iab thre there

" General config
set number                      "Line numbers
set visualbell                  "No sounds
set laststatus=2                "display the status line always
set confirm
set scrolloff=2                 "auto scroll text
set modeline                    "enable modline
set encoding=utf-8              "deflault encouding
set autowrite                   "prevent asking if you want to save the curbuf
set lazyredraw                  "don't redraw when don't have to
set mousemodel=popup            "enable a popup menu on right click in GUI vim
set sidescrolloff=5             "always at least five lines visible above/below
set virtualedit=block           "cursr can be positioned where there is no char
set splitright                  "make the new window appear on the right
set splitbelow                  "show split screens at the bottom of the screen
filetype indent on

" Colorscheme
syntax enable                   "turn on syntax highlighting
set background=light            "set background
set t_Co=256                    "terminal colors
colorscheme solarized           "set colorscheme

" Searching
set ignorecase                  "case insensitive search
set smartcase                   "if uppercase letter, it is case sensitive
set incsearch                   "move the cursor to the matched string
set hlsearch                    "highlight search matches

" Indentation
set tabstop=8                   "set how many columns a tab counts for
set expandtab                   "insert spaces on tab
set softtabstop=4               "set how many columns vim inserts on tab
set shiftwidth=4                "how many columns with >> and <<

" Title
set title                       "automaticly set vim windows title
set titlestring=VIM:\ %F

" Swap file location
set backupdir=~/.backup,.,/tmp
set directory=~/.backup,/tmp

set foldmethod=marker          "special chars to flag the start and end of fold
set mouse=a

if exists('+colorcolumn')
    set colorcolumn=80
endif

