# set locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export GIT_EDITOR=vim
export VISUAL=vim
export EDITOR=vim

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh/oh-my-zsh

# if tmux session active source custom conf file
if { [ -n "$TMUX" ]; } then
    tmux source-file ~/.tmux.conf > /dev/null
fi

# COMPLETION SETTINGS
# add custom completion scripts
fpath=(~/.zsh/completion $fpath)

ZSH_THEME="kphoen"

plugins=(zsh-completion git fabric docker docker-compose python pip brew)

source $ZSH/oh-my-zsh.sh

TERM=screen-256color

# Source virtualenvwrapper
if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    source /usr/local/bin/virtualenvwrapper.sh
fi

# if we have inherited virtualenv from parent session activate it
if [ $VIRTUAL_ENV ]; then
    . "$VIRTUAL_ENV/bin/activate"
fi

alias ta='tmux attach-session -t'
alias tn='tmux new-session -s'
alias tnn='TMUX= tmux new -d -s'
alias tl='tmux list-sessions'

alias sl='ls'
alias gs='git status'
alias update='brew update && brew upgrade'

# Python
export PYTHONSTARTUP=~/.pythonstartup.py

export DEVELOPMENT_ROOT=$HOME/Development
export PATH=$PATH:$DEVELOPMENT_ROOT/tools/bin

export SPARK_HOME=/usr/local/Cellar/apache-spark/1.6.2/libexec/
export PATH=$PATH:$SPARK_HOME/ec2

export PATH=$PATH:$HOME/.npm-packages/bin

source /usr/local/share/zsh/site-functions/_aws

source $DEVELOPMENT_ROOT/tools/dcos/bin/env-setup
