SHELL=/bin/zsh

# set locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export GIT_EDITOR=nvim
export VISUAL=nvim
export EDITOR=nvim

export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Add python
export PATH=$PATH:~/Library/Python/3.11/bin

export PATH=$PATH:~/workspace/bin

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh/oh-my-zsh

# if tmux session active source custom conf file
if { [ -n "$TMUX" ]; } then
    tmux source-file ~/.tmux.conf > /dev/null
fi

ZSH_THEME="kphoen"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'  # for dark theme
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=180' # for light theme

plugins=(zsh-autosuggestions zsh-syntax-highlighting git)

source $ZSH/oh-my-zsh.sh

PROMPT='[%~$(git_prompt_info)]
%# '

alias ta='tmux attach-session -t'
alias tn='tmux new-session -s'
alias tnn='TMUX= tmux new -d -s'
alias tl='tmux list-sessions'

alias sl='ls'
alias gs='git status'

alias vim='nvim'

alias logibomb="killall LogiMgrDaemon"

# Add go bin dir to path
export PATH=$PATH:$GOPATH/bin

function sourceNvm {
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}
sourceNvm

function sourcePy {
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
}

function resetMagnet {
    pmset displaysleepnow; sleep 5; caffeinate -u -t 1
}

NODE_OPTIONS=--max_old_space_size=2048

# fzf keybindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

